sudo: false

language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.20"
  - "5.20-shrplib"
  - "5.18"
  - "5.18-shrplib"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

before_install:
  - yes | perl -MCPAN::FirstTime -e CPAN::FirstTime::init
  - cpanm --notest App::ModuleBuildTiny Devel::Cover Devel::Cover::Report::Coveralls

script:
  PERL5OPT=-MDevel::Cover prove -Ilib -r t && cover -report coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true
